#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER mandel94 WITH ENCRYPTED PASSWORD '123456789';
	GRANT ALL PRIVILEGES ON DATABASE movie_db TO mandel94;
	CREATE DATABASE test_db;
	GRANT ALL PRIVILEGES ON DATABASE test_db TO mandel94;
EOSQL


