FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

# Install psycopg2 and other dependencies, including PostgreSQL development package
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "./src/client.py"]

